# Use an official Python runtime as a parent image
FROM python:3.5-slim    

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt

RUN pip install --no-cache-dir pandas numpy scikit-learn joblib matplotlib  Flask

# Expose any ports the app is expecting
EXPOSE 8080

# Run app.py when the container launches
CMD ["python", "app.py"]
